[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn asha_ai_chatbot.app.app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[envs]
PYTHON_VERSION = "3.9.0"
WEB_CONCURRENCY = "2" 