[build]
builder = "NIXPACKS"
buildCommand = "pip install wheel setuptools && pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "gunicorn wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[envs]
PYTHON_VERSION = "3.9.0"
WEB_CONCURRENCY = "2" 